name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test,dev]
    
    - name: Run basic tests
      run: python basic_test.py
    
    - name: Lint with black
      run: black --check ambivo_mcp_server/
    
    - name: Type check with mypy
      run: mypy ambivo_mcp_server/ --ignore-missing-imports
    
    - name: Check import sorting
      run: isort --check-only ambivo_mcp_server/
    
    # Uncomment when proper tests are added
    # - name: Run pytest
    #   run: pytest tests/ -v
    
    - name: Test package build
      run: |
        pip install build
        python -m build
        pip install dist/*.whl
        ambivo-mcp-server --help || echo "CLI test completed"